### ISSUE TITLE
timer functions should be bound-fns to allow eventbus replies to work

### ISSUE THREAD

**Issue by cocodrino** [vert-x/mod-lang-clojure#126]
hi...when I run this code I get an error

server

```clojure
(ns httpServerSlow
  (:require [vertx.http :as http]
            [vertx.eventbus :as ev]))



(ev/set-default-reply-timeout! 10000)

(defn req-handler [req]
  (println "got request")
  (ev/send "slowVerticle:hi" "hello"
           (fn [msg]
             (-> (http/server-response req)
                 (http/end msg)))))


(-> (http/server) (http/on-request req-handler) (http/listen 8080 "localhost"))

```
verticle

```clojure
(ns yourvertxproject.slowVerticles
  (:require [vertx.core :as vertx]
            [vertx.eventbus :as bus]
            [vertx.eventbus :as eb]))

(bus/on-message
  "slowVerticle:hi"
  (fn [m]
    (println "recibido mensaje " m)
    (vertx/timer 5000 (eb/reply "hello back"))))

```
```bash
Unexpected exception in Clojure verticle 
java.lang.NullPointerException
	at vertx.eventbus$reply_STAR_.invoke(eventbus.clj:225)
	at vertx.eventbus$reply.invoke(eventbus.clj:249)
	at yourvertxproject.slowVerticles$eval359$fn__360$fn__361.invoke(slowVerticles.clj:10)
	at vertx.core$as_handler$fn__234.invoke(core.clj:97)
	at vertx.core$as_handler$reify__238.handle(core.clj:101)
	at org.vertx.java.core.impl.DefaultVertx$InternalTimerHandler.run(DefaultVertx.java:432)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:123)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

Unexpected exception in Clojure verticle 
java.lang.NullPointerException
	at vertx.eventbus$reply_STAR_.invoke(eventbus.clj:225)
	at vertx.eventbus$reply.invoke(eventbus.clj:249)
	at yourvertxproject.slowVerticles$eval359$fn__360$fn__361.invoke(slowVerticles.clj:10)
	at vertx.core$as_handler$fn__234.invoke(core.clj:97)
	at vertx.core$as_handler$reify__238.handle(core.clj:101)
	at org.vertx.java.core.impl.DefaultVertx$InternalTimerHandler.run(DefaultVertx.java:432)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:123)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

```

the problem fixes when I use directly timer*

```clojure
(vertx/timer* 5000 (bound-fn [_] (eb/reply "hello back")))
```

the bound-fn is also required

**Comment by stream1984** [comment]
Excellent.  i have make more simple example, for test this issue

    (ns yourvertxproject.slowVerticles
    (:require [vertx.core :as vertx]
            [vertx.eventbus :as eb]))

    (eb/set-default-reply-timeout! 5000)

    (eb/on-message "eb.address"
               (fn [m]
                 (println "recibido mensaje " m)
                 (vertx/timer 1000 (eb/reply "hello back")))
               (fn [_]
                 (println "send message")
                 (eb/send "eb.address" "hello" (fn [msg] (println msg)))))

Master branch have fixed this tiny bug, waiting Toby make release.

**Comment by tobias** [comment]
@cocodrino thanks for the report, and @stream1984 thanks for the fix. I'll merge the fix in, but don't think it's worth making a release right now, especially since an easy workaround (using `bound-fn`) exists. I'll leave this issue open until we do release, in case anyone else stumbles over the issue.

**Comment by tobias** [comment]
Ah, right, there's nothing to merge in, since @stream1984 has push rights. So this is already fixed on master.
