### ISSUE TITLE
get null exception although everything seems works

### ISSUE THREAD

**Issue by cocodrino** [vert-x/mod-lang-clojure#132]
Hi..I've two questions:

1) continuously I get a null pointer exception
this happen when I communicate my event bus, the messages are received and reply fine but with every message I get this

```bas
Unexpected exception in Clojure verticle 
java.lang.NullPointerException
	at debgtest.samplevert$eval7403$fn__7404.invoke(samplevert.clj:9)
	at vertx.eventbus$message_handler$fn__7302.invoke(eventbus.clj:111)
	at vertx.core$as_handler$fn__234.invoke(core.clj:97)
	at vertx.core$as_handler$reify__238.handle(core.clj:101)
	at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:951)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

Unexpected exception in Clojure verticle 
java.lang.NullPointerException
	at debgtest.samplevert$eval7403$fn__7404.invoke(samplevert.clj:9)
	at vertx.eventbus$message_handler$fn__7302.invoke(eventbus.clj:111)
	at vertx.core$as_handler$fn__234.invoke(core.clj:97)
	at vertx.core$as_handler$reify__238.handle(core.clj:101)
	at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:951)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

Unexpected exception in Clojure verticle 
java.lang.NullPointerException
	at debgtest.core$init$fn__7382$fn__7383.invoke(core.clj:49)
	at vertx.eventbus$message_handler$fn__7302.invoke(eventbus.clj:111)
	at vertx.core$as_handler$fn__234.invoke(core.clj:97)
	at vertx.core$as_handler$reify__238.handle(core.clj:101)
	at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:951)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

Unexpected exception in Clojure verticle 
java.lang.NullPointerException
	at debgtest.core$init$fn__7382$fn__7383.invoke(core.clj:49)
	at vertx.eventbus$message_handler$fn__7302.invoke(eventbus.clj:111)
	at vertx.core$as_handler$fn__234.invoke(core.clj:97)
	at vertx.core$as_handler$reify__238.handle(core.clj:101)
	at org.vertx.java.core.eventbus.impl.DefaultEventBus$11.run(DefaultEventBus.java:951)
	at org.vertx.java.core.impl.DefaultContext$3.run(DefaultContext.java:175)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:370)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)
 ```

2) Are you tried debugging your deployed verticles?..sometimes I can only debug my main verticle using remote debugger, but the verticles than has been deployed by the main verticle (I'm using lein vertx) seems not works with the debugger (don't stop in the breakpoints), I'm using intellij idea, which has a  beta support for clojure, so if you has debugger correctly with other tool please let me know for give it a try.....

**Comment by tobias** [comment]
Can you share the code that is causing the NPE? What does line 49 of your core.clj look like?

I've never used a debugger with Vert.x (or with Clojure at all, for that matter), so I can't provide any insight there.

**Comment by cocodrino** [comment]
hi tobias..the line 49 is only  (fn[req] ...I test today the same code, without any change and it doesnt fails with NPE now...seems to be a bit unpredictable exception...
